### ISSUE TITLE
mypy issues with 2.7.2

### ISSUE THREAD

**Issue by dpinol** [okken/pytest-check#195]
How to reproduce:
1) Create an environment with python 3.14
2) Edit `examples/test_example_functions_pass.py` to replace `from pytest_check import check` with `import pytest_check as check`.
With the former, it looks like neither mypy nor pycharm are not able to see the function argument types.
3) `tox -e mypy`

Many errors like the following appear
```python
examples/test_example_functions_pass.py:82: error: Argument 1 to "greater" has incompatible type "int"; expected "_ComparableGreaterThan"  [arg-type]
        check.greater(2, 1)
                      ^
examples/test_example_functions_pass.py:82: note: Following member(s) of "int" have conflicts:
examples/test_example_functions_pass.py:82: note:     Expected:
examples/test_example_functions_pass.py:82: note:         def __gt__(self, object, /) -> bool
examples/test_example_functions_pass.py:82: note:     Got:
examples/test_example_functions_pass.py:82: note:         def __gt__(self, int, /) -> bool
examples/test_example_functions_pass.py:86: error: Argument 1 to "greater_equal" has incompatible type "int"; expected "_ComparableGreaterThanOrEqual"  [arg-type]
        check.greater_equal(2, 1)
```

The problem is probably caused by https://github.com/okken/pytest-check/commit/f08291f9cea56b4ca02f4d4aba54d4e09a9a68ce

**Comment by dpinol** [comment]
Sorry, `tox -e mypy` succeeds because it executes mypy without `--strict` for the examples. Try adding executing with `--strict` or typing the result of the test function to `None` so that mypy checks the types.

**Comment by okken** [comment]
I'll take that response as "this is good enough" for the strict fix.  
Also, I added some more type hint stuff so that the "from pytest_check import check" model works better with Intellisense. 
This makes coding hints show up with VSCode. 
I haven't tried it with PyCharm. Please let me know if it fixes it.

Changes are in [2.7.3](https://github.com/okken/pytest-check/releases/tag/2.7.3)

**Comment by okken** [comment]
Perhaps 2.7.4 (just released) might do the trick

**Comment by dpinol** [comment]
Hi, thanks again for the new release!
The int-float case is fixed. I only have this pending case, which is not a big deal.

```python   
 check.greater_equal(np.iinfo(np.float32).max, 0)
```

```
  test/utils/test_types.py: note: In function "test_NP_INT_TO_FLOAT":
  test/utils/test_types.py:37: error: Value of type variable "_IntegerT_co" of
  "iinfo" cannot be "floating[_32Bit]"  [type-var]
          check.greater_equal(np.iinfo(np.float32).max, 0)
```
